### ISSUE TITLE
Status 127 on Running convertGraph

### ISSUE THREAD

**Issue by claudiolucinda** [haghish/convertGraph#1]
Hi all,
I am finding some issues on running convertGraph in my Win10 RStudio machine. More specifically, when I run the convertGraph command, i find the following warning:

Warning message:
running command ''C:/Users/ClaudioLucinda/Dropbox/Git_Comprasnet/Comprasnet_Scraper/phantomjs-2.1.1-windows/bin/phantomjs.exe' C:/Users/ClaudioLucinda/Documents/R/win-library/3.4/convertGraph/lib/command.js ./Captchas/captcha.gif ./Captchas/captcha.png' had status 127

After reading somewhere on StackOverflow, I think I need to get something on my PATH variable. Is that correct? How should I proceed to solve this issue?

Best,
Claudio

**Comment by haghish** [comment]
not sure why you are getting this error. try using a usual path (both for phantomJS and your files) and test that the package is working on your machine... with this information I cannot help much

**Comment by claudiolucinda** [comment]
I have tried in several other directories with no sucess. Are there any other dependencies (Java, RTools) that should be in my OS PATH variable?

**Comment by haghish** [comment]
I don't think so... I'm not sure what is going wrong in your computer... I'd suggest that you use phantomJS from the terminal first, to make sure you can access it and it is working.

**Comment by claudiolucinda** [comment]
I tried running a "hello world" script from the command line and it ran smoothly. Then I put everything on the same place (phantomjs.exe, command.js and the GIF file) and ran the command just as in the R command, only through the command line. Then it generated an empty PNG file. 
Anyway, thanks for your time.

**Comment by mikeyEcology** [comment]
When I run convertGraph(), the only output I get is `127`, and no file is created. I'm also on Windows 10 and using RStudio. 

This is my input:
```
convertGraph(from= "C:/Users/.../image.bmp",
             to="C:/Users/.../image.jpg",
             path="C:/phantomjs-2.1.1-windows/bin/phantomjs.exe")
```
And my output is just `127`

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)
Matrix products: default
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] convertGraph_0.1
loaded via a namespace (and not attached):
[1] compiler_4.0.2 tools_4.0.2

**Comment by NicWir** [comment]
> When I run convertGraph(), the only output I get is `127`, and no file is created. I'm also on Windows 10 and using RStudio.
> 
> This is my input:
> 
> ```
> convertGraph(from= "C:/Users/.../image.bmp",
>              to="C:/Users/.../image.jpg",
>              path="C:/phantomjs-2.1.1-windows/bin/phantomjs.exe")
> ```
> 
> And my output is just `127`
> 
> > sessionInfo()
> > R version 4.0.2 (2020-06-22)
> > Platform: x86_64-w64-mingw32/x64 (64-bit)
> > Running under: Windows 10 x64 (build 18363)
> > Matrix products: default
> > locale:
> > [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252
> > [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C
> > [5] LC_TIME=English_United States.1252
> > attached base packages:
> > [1] stats     graphics  grDevices utils     datasets  methods   base
> > other attached packages:
> > [1] convertGraph_0.1
> > loaded via a namespace (and not attached):
> > [1] compiler_4.0.2 tools_4.0.2

This is exactly what happens to me on Windows 10 and RStudio 2021.09.2 Build 382. Did any solution come up to this?
